### ISSUE TITLE
[feature][Eldritch] Add function to obtain primary IP

### ISSUE THREAD

**Issue by KCarretto** [KCarretto/realm#139]
Would be great if we could obtain the IP address of the host an agent is running on in eldritch. This would have enabled us to more easily do a pwnboard check in across our fleet, striking joy in the hearts of red team.

**Comment by hulto** [comment]
We can add this to eldritch and probably should.
I think we should probably also add it to imix as a part of the callback function instead of using the imix config file.

**Comment by hulto** [comment]
Moved here.
https://github.com/KCarretto/realm/issues/149
