### ISSUE TITLE
Implement common encoding methods

### ISSUE THREAD

**Issue by KCarretto** [KCarretto/realm#146]
**Is your feature request related to a problem? Please describe.**
Eldritch does not yet have any built in support for common data encoding schemes such as base64 and json. Base64 encoding strings before executing them with sys.shell for example would help to remove odd quotation problems (in the event we don’t deploy an in memory script, e.g. the command was a parameter). 

**Describe the solution you'd like**
We should add the following methods to an encoding library:

* encoding.to_b64(data: str) -> str
* encoding.from_b64(data: str) -> str
* encoding.to_json(data: struct/map) -> str
* encoding.from_json(data: str) -> struct/map

Base64 support has a documented use case and would be more useful than JSON in the near term, but JSON is something we may want to support in the future.

**Describe alternatives you've considered** 
Not sure there are any alternatives that can help us achieve the desired results.

**Comment by jabbate19** [comment]
Can this go in the `crypto` module?
