### ISSUE TITLE
Improve documentation clarity around params & param defs expected values.

### ISSUE THREAD

**Issue by hulto** [KCarretto/realm#174]
**Is your feature request related to a problem? Please describe.**
The JSON schema is unclear for `tome.param_defs` & `job.parameters`.

Current documentation.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/7121375/227821000-64720385-627c-4e62-8b9e-215cfb6406d3.png">

Is this the right way to create a tome & job?

<img width="756" alt="image" src="https://user-images.githubusercontent.com/7121375/227821900-5f5d0e4f-e3e8-4f8b-992a-4372b7d0a9a5.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/7121375/227821998-9d9d95b9-362c-4de8-ba8d-2c4e45721b1e.png">

**Describe the solution you'd like**
- Adding some test data for jobs & tomes.
- Add a section to the Tavern API docs covering how the API works
  - Example of a full flow in the GraphQL playground. - Create Tome, Upload files, Create Job, ImixCallback, PostTaskResults, etc.
  - Could also be a good play to document some of the API schema choices, Eg. `createTome.param_defs` is named to clearly delineate between definition and values. `params` has dynamic keys wheres `param_defs` uses static keys since front end optimization requires knows dictionary keys and the c2 agent prefers named keys.

**Comment by hulto** [comment]
https://github.com/KCarretto/realm/pull/183/files#diff-fa1b96f1d93748162bca1d41ce119bd78819ce4ab500b91896a1f691eb860edeR511

Adds an example of what the agent expects for parameters & paramDefs.

**Comment by KCarretto** [comment]
This has been resolved
