### ISSUE TITLE
Unify rust testing

### ISSUE THREAD

**Issue by KCarretto** [KCarretto/realm#191]
**Is your feature request related to a problem? Please describe.**
Any time a new rust crate is added, a new Github workflow needs to be created to add it's testing to our CI/CD. 

**Describe the solution you'd like**
Merge these tests into one workflow that will automatically pick up new libraries if possible.

**Describe alternatives you've considered**
Having a thousand Github workflows 🤔

**Comment by hulto** [comment]
Blocked by #189

https://github.com/KCarretto/realm/issues/189
