### ISSUE TITLE
[feature] crypto.hash_file

### ISSUE THREAD

**Issue by jabbate19** [KCarretto/realm#275]
**Is your feature request related to a problem? Please describe.**
Eldritch doesn't have a way to hash a file

**Describe the solution you'd like**
`crypto.hash_file(src, method) -> String`

Most of the times I've had to hash in Rust I wrote it myself. There should be code in https://github.com/jabbate19/steeloxide somewhere

**Comment by hulto** [comment]
How would you feel about hashing variables instead that way we can use file.read and then sys.hash() 

Might want its own module for hash, encrypt, compress, encode.

**Comment by jabbate19** [comment]
We can make a different method for running crypto on data thats not a file imo

**Comment by hulto** [comment]
> We can make a different method for running crypto on data thats not a file imo

Works for me.
