### ISSUE TITLE
Add a "callback interval or next callback" field to tavern.

### ISSUE THREAD

**Issue by hulto** [KCarretto/realm#292]
**Is your feature request related to a problem? Please describe.**
Right now we aren't able to tell if a beacon has missed a callback/died. Ideally we'd display this clearly in the UI so users can remove or ignore dead beacons.

**Describe the solution you'd like**
Have imix report its next checkin or current callback interval during checkin or through a separate mutation.

**Describe alternatives you've considered**
Na 

**Additional context**
Na

**Comment by KCarretto** [comment]
This will be moved to the next release

**Comment by hulto** [comment]
Kyle:
"Then just need to add a field and update this code to set it from the proto. 
https://github.com/KCarretto/realm/blob/c122a523b01c4d5922270e4d6ab113185fa14b15/tavern/internal/c2/server.go#L69"

**Comment by KCarretto** [comment]
This is done
