### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by hulto** [KCarretto/realm#371]
**Is your feature request related to a problem? Please describe.**
The UI can encounter latency issues with requests taking up to 500ms to respond when populated with realistic data.

**Describe the solution you'd like**
To resolve this implement pagination so only the data needed immediately is fetched.

**Describe alternatives you've considered**

**Additional context**

**Comment by KCarretto** [comment]
@cmp5987 is this ready to be implemented? Did we agree on the spec?
