### ISSUE TITLE
[bug] Download_impl throws warning during compilation.

### ISSUE THREAD

**Issue by hulto** [KCarretto/realm#39]
**Describe the bug**
When compiling eldritch the download impl throws a warning of used Result.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/7121375/164934258-625d8990-b5af-469d-842f-824ec34d8056.png">

**To Reproduce**
1. cd ./implants/eldritch
2. cargo test test_download_file

**Additional context**
@Milkshak3s Sorry missed this during review when you get a chance can you push a PR.

**Comment by Milkshak3s** [comment]
Ohhhh yup can do
