### ISSUE TITLE
[feature] Add additional filtering to Tasks

### ISSUE THREAD

**Issue by cmp5987** [KCarretto/realm#392]
**Is your feature request related to a problem? Please describe.**

We want to move filtering from the frontend to the backend. We want to be able to filter tasks by host information including tags. Additionally, we want to be able to filter by host's platform.

**Describe the solution you'd like**

Please add the ability to query by hasHostWith. We wish to filter for host's tags and host's platform.

**Current behavior errors**
<img width="577" alt="Screenshot 2023-12-09 at 8 17 18 PM" src="https://github.com/KCarretto/realm/assets/32434695/1dafb1f7-8f70-465b-b32d-e1f99005deaa">
**Filtering allowed when directly querying tags**
<img width="920" alt="Screenshot 2023-12-09 at 8 17 47 PM" src="https://github.com/KCarretto/realm/assets/32434695/55545fdd-0628-42bd-bd56-cf621742bcbf">

**Comment by KCarretto** [comment]
@cmp5987 i believe this is resolved, just need to traverse Task --> Beacon --> Host --> Tag
